version: '2'
services:
  worker:
    container_name: payments
    image: maven:3.6.3-jdk-11-openj9 
    volumes:
      - ~/workspace/socialbank:/socialbank
      - ~/.m2:/root/.m2
    ports:
      - "8083:8080"

