version: '2'
services:
  db:
    container_name: oradb
    image: oracle/database:19.3.0-ee
    ports:
      - 1521:1521
      - 5500:5500
    shm_size: 1g
    volumes:
      - ./oradata:/opt/oracle/oradata
    environment:
      - ORACLE_PWD=Socialbank@2019
    restart: unless-stopped  
volumes:
  data: 
