version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    hostname: postgres
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loyalt
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "0.0.0.0:82:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: fernando@fernando.me
      PGADMIN_DEFAULT_PASSWORD: Fernando@2021
    restart: unless-stopped

volumes:
  postgres-data:
