version: '2'
services:
  mongo:
    container_name: mongo
    image: mongo
    environment:
      - "TZ=America/Sao_Paulo" # offset GMT +03:00
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
volumes:
  data: