version: '2'
services:
  db:
    container_name: sqlserver
    image: microsoft/mssql-server-windows-express
    ports:
      - 1433:1433
    shm_size: 1g
    volumes:
      - ./data:/u01/app/oracle/oradata
    environment:
      - sa_password=123456
      - ACCEPT_EULA=Y
    restart: unless-stopped  
volumes:
  data: 
