version: '2'
services:
  db:
    container_name: sqlserver
    image: microsoft/mssql-server-linux:latest
    ports:
      - 1433:1433
    shm_size: 1g
    volumes:
      - ./sqldata:/var/lib/sqldata
    environment:
      - SA_PASSWORD=Fernando@2021
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    restart: unless-stopped  
volumes:
  data: 
