version: '2'
services:
  webserver:
    container_name: sdk 
    image: sdk 
    ports:
      - 8080:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
      - SPRING_CONFIG_ADDITIONAL-LOCATION=/run/secrets/datasource.prod.properties,/run/secrets/credentials.prod.properties
    volumes:
      - '/run/secrets/:/run/secrets/'
