version: '2'
services:
  solr:
    container_name: solr
    image: solr
    ports:
     - "8983:8983"
    volumes:
      - ./search:/opt/solr/server/solr/search
      - ./mysql-connector-java-5.1.46.jar:/opt/solr/dist/mysql-connector-java-5.1.46.jar
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
volumes:
  data: